sudo: false
language: ruby

install: 'gem update --system; gem install bundler; bundle install --retry=3'
before_script: unset CI
script: 'ruby -vwr bundler/setup -S rake test'

matrix:
  include:
    - rvm: 2.4
      env: RUBYOPT=--enable-frozen-string-literal
    - rvm: 2.5
      env: RUBYOPT=--enable-frozen-string-literal
    - rvm: 2.6
      env: RUBYOPT=--enable-frozen-string-literal
    - rvm: 2.7
      env: RUBYOPT=--enable-frozen-string-literal
    - rvm: ruby-head
      env: RUBYOPT=--enable-frozen-string-literal
    - rvm: jruby
      env: JRUBY_OPTS=--debug
