sudo: false
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-9

before_install:
  - rvm get head
  - rvm reload
  - rvm use --install $TRAVIS_RUBY_VERSION --binary --fuzzy
install: 'bundle install --retry=3'
script: 'ruby -r bundler/setup -S rake test'
